[build]
  command = "yarn build"
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "20.18.0" }

[context.deploy-preview]
  environment = { NODE_VERSION = "20.18.0" }

[context.branch-deploy]
  environment = { NODE_VERSION = "20.18.0" }
